name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - name: Install Yarn Dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Run test
        run: yarn test
